<?php

namespace AppBundle\Repository;

/**
 * UserObservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserObservationRepository extends \Doctrine\ORM\EntityRepository
{
}
